# Generated by Django 4.0.5 on 2022-06-29 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Brandlar',
            },
        ),
        migrations.CreateModel(
            name='Madel',
            fields=[
                ('madel_id', models.AutoField(primary_key=True, serialize=False)),
                ('madel_name', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='telefonlar.brand')),
            ],
            options={
                'verbose_name_plural': 'Madellar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_title', models.TextField()),
                ('product_description', models.TextField()),
                ('product_price', models.IntegerField()),
                ('product_color', models.TextField()),
                ('product_memory', models.TextField()),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='telefonlar.brand')),
                ('product_madel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='telefonlar.madel')),
            ],
            options={
                'verbose_name_plural': 'Produktlar',
            },
        ),
    ]
